name       : OTPClient
version    : 2.3.1
release    : 2
source     :
    - https://github.com/paolostivanin/OTPClient/archive/v2.3.1.tar.gz : 691dfa024ffccf97233f313b3739092c1ae390edb8366f89b96054a98e512ea6
license    : GPL-3.0-or-later
component  : security
summary    : Highly secure and easy to use OTP client written in C/GTK that supports both TOTP and HOTP
description: |
    Highly secure and easy to use GTK+ software for two-factor authentication that supports both Time-based
    One-time Passwords (TOTP) and HMAC-Based One-Time Passwords (HOTP).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libgcrypt)
    - pkgconfig(libzip)
    - pkgconfig(libpng)
    - pkgconfig(cotp)
    - pkgconfig(zbar)
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install
