name       : OTPClient
version    : 2.5.1
release    : 10
source     :
    - https://github.com/paolostivanin/OTPClient/archive/v2.5.1.tar.gz : e35d4c004abc523428b9d40f01e18153d87e38073c2bd56ac855ecdcec14d47c
license    : GPL-3.0-or-later
component  : security
summary    : Highly secure and easy to use OTP client written in C/GTK that supports both TOTP and HOTP
description: |
    Highly secure and easy to use GTK+ software for two-factor authentication that supports both Time-based One-time Passwords (TOTP) and HMAC-Based One-Time Passwords (HOTP).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libgcrypt)
    - pkgconfig(libzip)
    - pkgconfig(libpng)
    - pkgconfig(cotp)
    - pkgconfig(zbar)
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install
