name       : OTPClient
version    : 2.4.8
release    : 8
source     :
    - https://github.com/paolostivanin/OTPClient/archive/v2.4.8.tar.gz : 252dd4cad71ea19f26686a8c6cfdb12fb25100cb98694fd36eec1a4d28f39a23
license    : GPL-3.0-or-later
component  : security
summary    : Highly secure and easy to use OTP client written in C/GTK that supports both TOTP and HOTP
description: |
    Highly secure and easy to use GTK+ software for two-factor authentication that supports both Time-based One-time Passwords (TOTP) and HMAC-Based One-Time Passwords (HOTP).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libgcrypt)
    - pkgconfig(libzip)
    - pkgconfig(libpng)
    - pkgconfig(cotp)
    - pkgconfig(zbar)
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install
