name       : OTPClient
version    : 2.2.1
release    : 1
source     :
    - https://github.com/paolostivanin/OTPClient/archive/v2.2.1.tar.gz : d9b02517ad571a7d9aca09c6650853e9a3bc4ef70cbe05e75b7b03196e486459
license    : GPL-3.0-or-later
component  : security
summary    : Highly secure and easy to use OTP client written in C/GTK that supports both TOTP and HOTP 
description: |
    Highly secure and easy to use GTK+ software for two-factor authentication that supports both Time-based
    One-time Passwords (TOTP) and HMAC-Based One-Time Passwords (HOTP).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libgcrypt)
    - pkgconfig(libzip)
    - pkgconfig(libpng)
    - pkgconfig(cotp)
    - pkgconfig(zbar)
setup: |
    %cmake -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install
